### ISSUE TITLE
怎么有两个一样的？

### ISSUE THREAD

**Issue by tankxxl** [ksharpdabu/MultiImageSelector-master#1]
https://github.com/lovetuzitong/MultiImageSelector
![image](https://cloud.githubusercontent.com/assets/1826540/9760581/e3789fac-5728-11e5-8b7b-4b29d562c42a.png)

**Comment by ksharpdabu** [comment]
原作者就是https://github.com/lovetuzitong/MultiImageSelector 。我这里只是备份下，建议有问题去原作者那里留言。
